spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration-in-ms: 86400000

server:
  port: 8080

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    token-uri: https://oauth2.googleapis.com/token
    issuer: https://accounts.google.com
    jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

course-sync:
  auto:
    fixedDelayMillis: 10800000 # 3시간 (자유롭게 수정)
  sugang:
    excelUrl: "https://sugang.snu.ac.kr/sugang/cc/cc100InterfaceExcel.action"
    refererUrl: "https://sugang.snu.ac.kr/sugang/cc/cc100InterfaceSrch.action"
    pageSize: 9999
    language: "ko"
    connectTimeoutMillis: 5000
    readTimeoutMillis: 30000
  defaultTarget:
    year: 2026
    semester: SPRING


# AWS S3 설정 (prod 환경에서만 활성화)
aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION:ap-northeast-2}
    base-url: ${AWS_S3_BASE_URL}
    presigned-url-expiration-minutes: ${AWS_S3_PRESIGNED_URL_EXPIRATION_MINUTES:15}